export { default as userRoutes } from './user.routes.js'
export { default as menuRoutes } from './menu.routes.js'
export { default as orderRoutes } from './order.routes.js'
export {default as categoryRoutes } from './category.routes.js'
export { default as loginRoutes } from './login.routes.js'